import { Col, Container, Row } from "react-bootstrap";
import styles from "@/styles/home/contact.module.scss"

export const metadata = {
    title: "Contact Page | Cloud Studios",
    description: "Generated by create next app",
};
export default function ContactPage() {
    return (
        <section className={`${styles.contactSec} ${styles.contactStyle} p-100 `}>
            <Container className="h-100">
                <Row>
                    <Col xxl={12} lg={12} md={12} className="text-center my-auto">
                        <div className={styles.contactBg}>
                            <h2 className="spacing">Thank You</h2>
                            <p>Welcome to the community, your personalized experience awaits!</p>
                        </div>
                    </Col>
                </Row>

            </Container>
        </section>
    );
}
