import Contact from "@/src/app/home/contact";
export const metadata = {
    title: "Contact Page | Cloud Studios",
    description: "Generated by create next app",
};
export default function ContactPage() {
    return (
        <>
            <Contact page="contact" />
        </>
    );
}
